version: "3"

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: lucas
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: changeme
      ME_CONFIG_MONGODB_PORT: 27017

  mongo:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  dbdata:
  redisdata:
